#!/usr/bin/env python3
"""Regenerate the weekly-report's vendored assets (fonts.css, icons.svg).

Dev-time only — the generated files are committed, so rendering a report never
touches the network. Re-run only to add an icon or change a font.

  python3 build-assets.py            # rebuild both
  python3 build-assets.py --icons    # icons only

Fonts come from Google Fonts (Inter, JetBrains Mono — both OFL), icons from
Phosphor (MIT). Only the `latin` subset of each font is kept; base64-inlining
every subset would quadruple the file for glyphs a report never renders.
"""
import argparse
import base64
import re
import subprocess
import sys
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "assets"

FONT_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600"
    "&family=JetBrains+Mono:wght@400;500;700"
    "&display=swap"
)
# Google serves woff2 only to browser-like UAs; a bare curl gets legacy ttf.
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# name -> (phosphor-icon, style). Keep in sync with what template.html references.
ICONS = {
    "stack": ("stack", "regular"),
    "brain": ("brain", "regular"),
    "rocket": ("rocket-launch", "regular"),
    "chart": ("chart-line-up", "regular"),
    "shield": ("shield-check", "regular"),
    "database": ("database", "regular"),
    "globe": ("globe", "regular"),
    "gear": ("gear", "regular"),
    "bug": ("bug", "regular"),
    "sparkle": ("sparkle", "regular"),
    "git-branch": ("git-branch", "regular"),
    "git-merge": ("git-merge", "regular"),
    "tree": ("tree-structure", "regular"),
    "user": ("user", "regular"),
    "list": ("list-checks", "regular"),
    "ticket": ("ticket", "regular"),
    "flag": ("flag", "regular"),
    "check": ("check", "regular"),
    "circle-notch": ("circle-notch", "regular"),
    "lock": ("lock-simple", "regular"),
    "lock-open": ("lock-simple-open", "regular"),
    "warning": ("warning", "fill"),
    "target": ("target", "fill"),
    "github": ("github-logo", "regular"),
}

PHOSPHOR = "https://cdn.jsdelivr.net/npm/@phosphor-icons/core@2.1.1/assets/{style}/{file}.svg"


def fetch(url: str, ua: bool = False) -> bytes:
    cmd = ["curl", "-sSfL", "--max-time", "30"]
    if ua:
        cmd += ["-H", f"User-Agent: {UA}"]
    cmd.append(url)
    out = subprocess.run(cmd, capture_output=True)
    if out.returncode != 0:
        raise SystemExit(f"fetch failed: {url}\n{out.stderr.decode()}")
    return out.stdout


def build_fonts() -> None:
    css = fetch(FONT_CSS_URL, ua=True).decode()
    # Blocks are emitted as: /* subset */\n@font-face { ... }
    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    kept = [(s, b) for s, b in blocks if s == "latin"]
    if not kept:
        raise SystemExit("no latin subsets found — did the Google Fonts CSS format change?")

    out = [
        "/* GENERATED by scripts/build-assets.py — do not edit.",
        "   Inter + JetBrains Mono (SIL Open Font License 1.1), latin subset, base64-inlined",
        "   so a report renders identically with no network. */",
        "",
    ]
    for _subset, block in kept:
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        b64 = base64.b64encode(fetch(m.group(1))).decode()
        block = block.replace(m.group(1), f"data:font/woff2;base64,{b64}")
        # unicode-range is pointless once there is exactly one subset per weight
        block = re.sub(r"\s*unicode-range:[^;]+;", "", block)
        out.append(block.strip())
        out.append("")

    path = ASSETS / "fonts.css"
    path.write_text("\n".join(out))
    print(f"fonts.css  {len(kept)} faces  {path.stat().st_size // 1024}KB")


def build_icons() -> None:
    out = [
        "<!-- GENERATED by scripts/build-assets.py — do not edit.",
        "     Phosphor Icons (MIT) — https://phosphoricons.com -->",
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">',
    ]
    for name, (file, style) in ICONS.items():
        suffix = "-fill" if style == "fill" else ""
        svg = fetch(PHOSPHOR.format(style=style, file=f"{file}{suffix}")).decode()
        body = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg, flags=re.S).strip()
        out.append(f'  <symbol id="i-{name}" viewBox="0 0 256 256">{body}</symbol>')
    out.append("</svg>")

    path = ASSETS / "icons.svg"
    path.write_text("\n".join(out) + "\n")
    print(f"icons.svg  {len(ICONS)} symbols  {path.stat().st_size // 1024}KB")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts", action="store_true")
    ap.add_argument("--icons", action="store_true")
    a = ap.parse_args()
    both = not (a.fonts or a.icons)
    ASSETS.mkdir(parents=True, exist_ok=True)
    if a.fonts or both:
        build_fonts()
    if a.icons or both:
        build_icons()
